name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      # Setup
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - uses: actions/setup-node@v2

      # Install packaging tools
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Install appdmg
        run: npm install -g appdmg

      # Build and package
      - name: Packaging .dmg
        run: flutter_distributor package --platform macos --targets dmg --artifact-name TerminalStudio-${{github.ref_name}}-macos.dmg

      # Publish
      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*/*

  build_windows:
    runs-on: windows-latest
    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      # Install packaging tools
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      # Build and package
      - name: Packaging .msix .zip
        run: flutter_distributor package --platform windows --targets msix,zip --artifact-name "TerminalStudio-${{github.ref_name}}-windows.{{ext}}"

      # Publish
      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*/*

  build_linux:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      # Install packaging tools
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      # Build and package
      - name: Packaging .deb .zip
        run: flutter_distributor package --platform linux --targets deb,zip --artifact-name "TerminalStudio-${{github.ref_name}}-linux.{{ext}}"

      # Publish
      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*/*
