name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      # Setup
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - uses: actions/setup-node@v2

      # Build
      - name: Build macOS
        run: flutter build macos

      # Install packaging tools
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Install appdmg
        run: npm install -g appdmg

      # Packaging
      - name: Packaging .dmg
        run: flutter_distributor package --platform macos --targets dmg --artifact-name TerminalStudio-${{github.ref_name}}-macos.dmg

      # Publish
      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/TerminalStudio-${{github.ref_name}}-macos.dmg
