name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      # Build for macOS
      - name: Build macOS
        run: flutter build macos

      # Upload the app as an artifact
      - name: Package macOS
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: TerminalStudio-${{github.ref_name}}-macos.zip
          directory: build/macos/Build/Products/Release

      # Publish the artifact
      - name: Release macOS
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/macos/Build/Products/Release/TerminalStudio-${{github.ref_name}}-macos.zip
